
charset: UTF-8

type: file

template:
  path: generator-test/src/main/resources/template/beetl

  config:
    Mapper.java.btl: mapper/${className}Mapper.java
    Dao.java.btl: mapper/${className}Dao.java
    ~zip!: ${outDir}/file/package.zip #输出为zip
  data:
    className: User
    package: user
    author: 'yyc'
    content: 'create by file, author: yyc'
    outDir: generator-out/beetl
