
charset: UTF-8

type: file

template:
  path: generator-test/src/main/resources/template/beetl

  config:
    Mapper.java.btl: ${outDir}/file/${className}Mapper.java
  data:
    className: User
    package: user
    author: 'yyc'
    content: 'create by file, author: yyc'
    outDir: generator-out/beetl
