
charset: UTF-8

type: classpath

template:
  path: template/beetl

  config:
    Mapper.java.btl: ${outDir}/classpath/${className}Mapper.java
    Dao.java.btl: ${outDir}/classpath/${className}Dao.java
  data:
    className: User
    package: user
    author: 'yyc'
    content: 'create by classpath, author: yyc'
    outDir: generator-out/beetl
