
charset: UTF-8

type: file

template:
  path: generator-test/src/main/resources/template/velocity

  config:
    Mapper.java.vm: ${outDir}/file/${className}Mapper.java
    Dao.java.vm: ${outDir}/file/${className}Dao.java
  data:
    className: User
    package: user
    author: 'yyc'
    content: 'create by file, author: yyc'
    outDir: generator-out/velocity
