
charset: UTF-8

type: file

template:
  path: generator-test/src/main/resources/template/freemarker

  config:
    Mapper.java.ftl: ${outDir}/file/${className}Mapper.java
    Dao.java.ftl: ${outDir}/file/${className}Dao.java
  data:
    className: User
    package: user
    author: 'yyc'
    content: 'create by file, author: yyc'
    outDir: generator-out/freemarker
